### ISSUE TITLE
CDF_PATH environment variable

### ISSUE THREAD

**Issue by kkotyk** [SuperDARN/rst-docker-files#2]
Until the CDF_PATH environment variable is changed in RST, the Dockerfiles are configured to change this variable in the bashrc. This can be removed later.

**Comment by egthomas** [comment]
Can we now delete the last line of each docker file and change the second-to-last line to something like the following?

`RUN printf "export RSTPATH=/root/rst\n. \$RSTPATH/.profile.bash >> /root/.bashrc`

**Comment by kkotyk** [comment]
I will add that right away

**Comment by egthomas** [comment]
I'm closing this now that #4 is merged.
