### ISSUE TITLE
Debian docker file

### ISSUE THREAD

**Issue by egthomas** [SuperDARN/rst-docker-files#3]
I haven't tried creating or using a docker file yet but I was able to get RST running on Debian 8.7.1, so maybe this will be of some use.  For whatever reason Debian doesn't have sudo installed by default, so I had to follow the instructions here:

https://www.privateinternetaccess.com/forum/discussion/18063/debian-8-1-0-jessie-sudo-fix-not-installed-by-default

Otherwise these were the packages necessary for compiling the RST.  I also had to follow the CDF download/make steps included in the Ubuntu and openSUSE docker files.

apt-get install vim
apt-get install sudo
(see link above)
apt-get install gcc
apt-get install git
apt-get install libhdf5-serial-dev
apt-get install libncurses-dev
apt-get install libnetcdf-dev
apt-get install libpng12-dev
apt-get install libx11-dev
apt-get install libxext-dev
apt-get install make

**Comment by kkotyk** [comment]
Docker set up automatically runs as root, so you should be able to add RUN commands to all of those installs.

**Comment by egthomas** [comment]
Ok that made things easy enough then.  I've created a dockerfile for debian-8.7 ( b703c24 ); tomorrow I may try creating one for Mint since I've also done a VM installation of RST on that distro.
